services:
#    Stunt.example:
#        class: StuntBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.accept_pd_processing_listener:
        class: StuntBundle\Listener\KernelRequestListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: checkPdProcessingAccepted }

    authentication_handler:
        class: StuntBundle\Security\Authentication\AuthenticationHandler
        arguments: ["@router", "@service_container"]
        tags:
              - { name: "monolog.logger", channel: "security" }

    auth_resolver:
        class: StuntBundle\Service\AuthResolver
        arguments: ["@service_container"]

    model.maintenance:
        class: StuntBundle\Model\Maintenance\MaintenanceModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.security:
        class: StuntBundle\Model\SecurityModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.user:
        class: StuntBundle\Model\UserModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
