# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.assets.versioning.gulp_buster:
        class: MainBundle\Asset\VersionStrategy\GulpBusterVersionStrategy
        arguments:
            - "%kernel.root_dir%/../busters.json"
            - "%%s?version=%%s"
        public: false