services:
#    blagost.example:
#        class: BlagostBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.accept_pd_processing_listener:
        class: BlagostBundle\Listener\KernelRequestListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: checkPdProcessingAccepted }

    authentication_handler:
        class: BlogBundle\Security\Authentication\AuthenticationHandler
        arguments: ["@router", "@service_container"]
        tags:
              - { name: "monolog.logger", channel: "security" }

    auth_resolver:
        class: BlogBundle\Service\AuthResolver
        arguments: ["@service_container", "@router"]

    password_generator:
        class: BlogBundle\Service\PasswordGenerator
        arguments: []

    model.congregant:
        class: BlogBundle\Model\CongregantModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.maintenance:
        class: BlogBundle\Model\Maintenance\MaintenanceModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.personal_data:
        class: BlogBundle\Model\PersonalDataModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.security:
        class: BlogBundle\Model\SecurityModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.user:
        class: BlogBundle\Model\UserModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    model.cashier:
        class: BlagostBundle\Model\CashierModel
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
