#main:
#    resource: "@MainBundle/Controller/"
#    type:     annotation
#    prefix:   /
default:
    path: /
    defaults: { _controller: "MainBundle:Default:index" }
    options:
        expose: true

# Security
registration:
    path: /register
    defaults: { _controller: "MainBundle:Security:registration" }

login:
    path: /login
    defaults: { _controller: "MainBundle:Security:login" }

logout:
    path: /logout

forgot_password:
    path: /forgot_password
    defaults: { _controller: "MainBundle:Security:forgotPassword" }

members_index:
    path: /members
    defaults: { _controller: "MainBundle:Members:index" }

memberss_profile:
    path: /members/profile
    defaults: { _controller: "MainBundle:Members:profile" }