#main:
#    resource: "@MainBundle/Controller/"
#    type:     annotation
#    prefix:   /
default:
    path: /
    defaults: { _controller: "MainBundle:Default:index" }
    options:
        expose: true

# Security
registration:
    path: /register
    defaults: { _controller: "MainBundle:Security:registration" }

login:
    path: /login
    defaults: { _controller: "MainBundle:Security:login" }

logout:
    path: /logout

forgot_password:
    path: /forgot_password
    defaults: { _controller: "MainBundle:Security:forgotPassword" }

admin_index:
    path: /admin
    defaults: { _controller: "MainBundle:Admin:index" }

admin_profile:
    path: /admin/profile
    defaults: { _controller: "MainBundle:Admin:profile" }

store_keeper_index:
    path: /storekeeper
    defaults: { _controller: "MainBundle:StoreKeeper:index" }

storage_index:
    path: /storage
    defaults: { _controller: "MainBundle:StoreKeeper:productOnStorage" }

worker_create_storage_index:
    path: /storage/createStorage
    defaults: { _controller: "MainBundle:StoreKeeper:createStorage" }

store_keeper_add_product_index:
    path: /storekeeper/addProduct
    defaults: { _controller: "MainBundle:StoreKeeper:addProduct" }

worker_add_stock_index:
    path: /storage/addStock
    defaults: { _controller: "MainBundle:StoreKeeper:addStock" }

worker_add_store_index:
    path: /storage/addStore
    defaults: { _controller: "MainBundle:StoreKeeper:addStore" }

admin_user_list:
    path: /admin/user/list
    defaults: { _controller: "MainBundle:Admin:listUsers" }